apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spa-frontend
  template:
    metadata:
      labels:
        app: spa-frontend
    spec:
      containers:
      - name: spa-frontend-app
        image: edupoli/spa-frontend:v1.0.1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '100m'
            memory: '256Mi'
          requests:
            cpu: '25m'
            memory: '64Mi'
        env:
          - name: NODE_ENV
            value: "production"
          - name: VITE_BACKEND_URL
            value: "https://${VITE_BACKEND_URL}"
          - name: VITE_PUBLIC_API_URL
            value: "https://${VITE_PUBLIC_API_URL}"
          - name: VITE_RECAPTCHA_SITE_KEY
            value: "${VITE_RECAPTCHA_SITE_KEY}"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
---

apiVersion: v1
kind: Service
metadata:
  name: spa-frontend-svc
spec:
  selector:
    app: spa-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
